package be.unamur.info.b314.compiler.emj;

import be.unamur.info.b314.compiler.EMJParser;


import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.*;


/*
Visitor class for the EMJ language, extending the base visitor class generated by ANTLR
@author : Alix Decrop
@version : 1.0
*/
public class EMJVisitor extends be.unamur.info.b314.compiler.EMJParserBaseVisitor<Object> {

    private EMJErrorLogger errorLogger;
    private ArrayList<String> varIds;

    public EMJVisitor() {
        this.errorLogger = new EMJErrorLogger();
        this.varIds = new ArrayList<String>();
    }

    public EMJErrorLogger getErrorLogger() {
        return this.errorLogger;
    }

    /*
    SEMANTIC_VAR_DECL
    */


//table de symbole


    private final Deque<Scope> scopes = new ArrayDeque<>();
    private Scope currentscope;


    private static final String type_int = "int";

    private static final String type_char = "char";


    private static final String type_string = "string";


    private static final String type_bool = "bool";

    private static final String type_void = "void";


    private static final String type_tuple_prefix = "tuple";


    //scope
    {
        pushscope(new Scope(null, scopetype.GLOBAL));
    }


    private void pushscope(Scope scope) {
        scopes.push(scope);

        currentscope = scope;


    }


    private void popscope() {
        scopes.pop();
        currentscope = scopes.peek();


    }


    private void adderreur(String code, String text, int ligne) {

        errorLogger.addError(new EMJError(code, text, ligne));
        ;


    }


    private String typedutypecontext(EMJParser.TypeContext ctx) {

        if (ctx.INT_TYPE() != null) return type_int;
        if (ctx.CHAR_TYPE() != null) return type_char;
        if (ctx.STRING_TYPE() != null) return type_string;
        if (ctx.BOOL_TYPE() != null) return type_bool;

        if (ctx.TUPLE_TYPE() != null) {
            String inner = typedutypecontext(ctx.type());
            return type_tuple_prefix + "<" + inner + ">";
        }

        return null;
    }


    private String typedufonctype(EMJParser.FonctypeContext ctx) {

        if (ctx.type() != null) return typedutypecontext(ctx.type());

        return type_void;


    }


    private boolean iscompatible(String expect, String actuel) {
        if (expect == null || actuel == null) return false;
        return expect.equals(actuel);
    }

    private String getTermeType(EMJParser.TermeContext ctx) {
        boolean hasOp = !ctx.FOIS().isEmpty() || !ctx.SLASH().isEmpty();
        String firstType = null;

        for (int i = 0; i < ctx.SLASH().size(); i++) {
            EMJParser.FacteurContext divisorCtx = ctx.facteur(i + 1);
            Integer val = evalfacteurconst(divisorCtx);
            if (val != null && val == 0) adderreur("DIV_ZERO", "division by zero", divisorCtx.start.getLine());
        }

        for (EMJParser.FacteurContext facteurContext : ctx.facteur()){
            String t = getexpressiontype(facteurContext);
            if (firstType == null) firstType = t;
            if (hasOp && !type_int.equals(t)) {
                adderreur("TYPE_ERR", "expected int in arithmetic expression, got " + t, facteurContext.start.getLine());
            }
        }
        return hasOp ? type_int : firstType;
    }

    private String getexpressiontype(EMJParser.ExpressionentiereContext ctx) {

        boolean hasOp = !ctx.PLUS().isEmpty() || !ctx.MINUS().isEmpty();
        String firstType = null;

        for (EMJParser.TermeContext termeContext : ctx.terme()) {
            String t = getTermeType(termeContext);
            if (firstType == null) firstType = t;
            if (hasOp && !type_int.equals(t)) {
                adderreur("TYPE_ERR", "expected int in arithmetic expression, got " + t, termeContext.start.getLine());
            }
        }
        return hasOp ? type_int : firstType;
    }


    private String getexpressiontype(EMJParser.ExpressiongaucheContext ctx) {
        String varname = ctx.EMOJI_ID().getText();
        Symbol s = currentscope.lookup(varname, false);
        if (s == null || !(s instanceof Variablesymbol)) {
            // AJOUTEZ CETTE LIGNE POUR SIGNALER L'ERREUR
            adderreur("var not declared", "variable " + varname + " not declared", ctx.start.getLine());
            return null;
        }
        String vartype = ((Variablesymbol) s).type;
        if (ctx.INDEX_ONE() != null || ctx.INDEX_TWO() != null) {
            if (vartype.startsWith(type_tuple_prefix)) {
                return vartype.substring(type_tuple_prefix.length() + 1, vartype.length() - 1);
            }
            return null;
        }
        return vartype;
    }


    private String getexpressiontype(EMJParser.ExpressiondroiteContext ctx) {


        if (ctx.expressionboolean() != null) return getexpressiontype(ctx.expressionboolean());


        if (ctx.expressionentiere() != null) return getexpressiontype(ctx.expressionentiere());

        if (ctx.expressiongauche() != null) return getexpressiontype(ctx.expressiongauche());

        if (ctx.CHAR_APP() != null) return type_char;

        if (ctx.STRING_GUILL() != null) return type_string;

        if (ctx.tuple() != null) return getexpressiontype(ctx.tuple());


        return null;


    }

    private String getRelationType(EMJParser.RelationContext ctx) {

        if (ctx.TRUE() != null || ctx.FALSE() != null) return type_bool;

        if (ctx.NOT() != null) return getRelationType(ctx.relation());

        if (ctx.expressionboolean() != null) return getexpressiontype(ctx.expressionboolean());

        if (ctx.expressionentiere().size() == 2) {
            String t1 = getexpressiontype(ctx.expressionentiere(0));
            String t2 = getexpressiontype(ctx.expressionentiere(1));

            if (!iscompatible(t1, t2))
                adderreur("TYPE_MISMATCH", "cannot compare " + t1 + " with " + t2, ctx.start.getLine());

            return type_bool;
        }

        return null;
    }


    private String getexpressiontype(EMJParser.ExpressionbooleanContext ctx) {

        for (EMJParser.RelationContext rel : ctx.relation()) {
            String t = getRelationType(rel);
            if (t != null && !t.equals(type_bool)) {
                adderreur("TYPE_ERR", "expected boolean expression, got " + t, ctx.start.getLine());
            }
        }

        return type_bool;
    }

    private String getexpressiontype(EMJParser.TupleContext ctx) {

        String t1 = getexpressiontype(ctx.expressiondroite(0));
        String t2 = getexpressiontype(ctx.expressiondroite(1));

        if (t1 == null || t2 == null) return null;
        if (!t1.equals(t2)) {
            adderreur("TYPE_MISMATCH", "tuple elements must be of the same type", ctx.start.getLine());
            return null;
        }

        return type_tuple_prefix + "<" + t1 + ">";
    }


    private String getexpressiontype(EMJParser.FacteurContext ctx) {

        if (ctx.MINUS() != null) {
            String t = getexpressiontype(ctx.facteur());
            if (t != null && !t.equals(type_int)) {
                adderreur("invalid neg", "negation only works on int", ctx.start.getLine());
            }
            return type_int;
        }

        if (ctx.INT_VALUE() != null) {
            validateintproblem(ctx.INT_VALUE().getText(), ctx.start.getLine());
            return type_int;
        }


        if (ctx.expressiongauche() != null) {
            return getexpressiontype(ctx.expressiongauche());
        }


        if (ctx.appelfonction() != null) {
            visitAppelfonction(ctx.appelfonction());
            String t = getfunctionreturntype(ctx.appelfonction());
            if (type_void.equals(t)) {
                adderreur("void func", "cannot use void function in expression", ctx.start.getLine());
                return null;
            }
            return t;
        }


        if (ctx.expressionentiere() != null) return getexpressiontype(ctx.expressionentiere());


        return null;


    }


    private String getfunctionreturntype(EMJParser.AppelfonctionContext ctx) {

        String funcnom = ctx.EMOJI_ID().getText();

        Symbol s = currentscope.lookup(funcnom, true);

        if (s instanceof Functionsymbol) return ((Functionsymbol) s).returntype;


        return null;


    }


    @Override
    public Object visitRoot(EMJParser.RootContext ctx) {

        if (ctx.carte() != null) visit(ctx.carte());


        else if (ctx.programme() != null) visit(ctx.programme());

        else if (ctx.instruction() != null) visit(ctx.instruction());


        else adderreur("no roooot", "non valide", ctx.start.getLine());


        return null;


    }


    @Override
    public Object visitCarte(EMJParser.CarteContext ctx) {

        int policecnt = 0;


        int thiefcnt = 0;


        int roadcnt = 0;


        int totals = 0;


        int width = Integer.parseInt(ctx.INT_VALUE(0).getText());


        int height = Integer.parseInt(ctx.INT_VALUE(1).getText());

        if (width < 2 || height < 2)
            adderreur("invalid dim", "width and height must be at least 2", ctx.start.getLine());

        int excpectedtils = width * height;


        EMJParser.LignescarteContext lignes = ctx.lignescarte();


        for (EMJParser.LignecarteContext ligne : lignes.lignecarte()) {

            for (EMJParser.CasecarteContext c : ligne.casecarte()) {
                totals++;
                if (c.POLICE() != null) policecnt++;
                if (c.BARAGE() != null) thiefcnt++;


                if (c.ROUTE() != null) roadcnt++;


            }


        }


        if (policecnt != 1)


            adderreur("invalid police", "1  police required ", ctx.start.getLine());

        if (thiefcnt < 1)


            adderreur("non thief", "1 thief required ", ctx.start.getLine());


        if (roadcnt == 0)
            adderreur("no road", "1 road required", ctx.start.getLine());


        if (totals != excpectedtils)
            adderreur("invalid  dimensions", "expected " + excpectedtils + " " + totals, ctx.start.getLine());

        return null;


    }


    @Override
    public Object visitProgramme(EMJParser.ProgrammeContext ctx) {


        premierepasse(ctx.mainfonction());
        for (EMJParser.FonctionContext f : ctx.fonction()) {
            premierepasse(f);
        }

        deuxiemepasse(ctx.mainfonction());


        for (EMJParser.FonctionContext f : ctx.fonction()) {


            deuxiemepasse(f);

        }

        return null;

    }


    private void premierepasse(EMJParser.MainfonctionContext ctx) {


        String funcnom = "main";


        if (currentscope.symbols.containsKey(funcnom)) {

            adderreur("défini", "already déf", ctx.start.getLine());

            return;
        }


        Functionsymbol mainsym = new Functionsymbol(funcnom, type_void, new ArrayList<>());


        currentscope.define(mainsym);


    }


    private void premierepasse(EMJParser.FonctionContext ctx) {


        String funcnom = ctx.EMOJI_ID().getText();


        String returntype = typedufonctype(ctx.fonctype());


        List<Parametersymbol> params = new ArrayList<>();


        Set<String> paramnoms = new HashSet<>();


        if (currentscope.symbols.containsKey(funcnom)) {


            adderreur("func définie", "func " + funcnom + " already définie", ctx.start.getLine());


            return;


        }


        if (ctx.parametres() != null) {


            for (EMJParser.ParametreContext p : ctx.parametres().parametre()) {


                String paramtype = typedutypecontext(p.type());


                String paramnom = p.EMOJI_ID().getText();


                if (paramnoms.contains(paramnom)) {
                    adderreur("dup param", "param " + paramnom + " dup", p.start.getLine());


                } else {


                    paramnoms.add(paramnom);


                    params.add(new Parametersymbol(paramnom, paramtype));


                }
            }


        }


        Functionsymbol funcsym = new Functionsymbol(funcnom, returntype, params);


        currentscope.define(funcsym);


    }


    private void deuxiemepasse(EMJParser.MainfonctionContext ctx) {


        Symbol s = currentscope.lookup("main", true);


        if (!(s instanceof Functionsymbol)) return;


        pushscope(new Scope(currentscope, scopetype.FUNCTION, (Functionsymbol) s));


        for (EMJParser.InstructionContext instr : ctx.instruction()) visit(instr);


        EMJParser.Return_instruContext ret = ctx.return_instru();


        if (ret == null) {
            adderreur("miss return", "end return missing", ctx.start.getLine());


        } else {

            String rettype = getreturntype(ret);


            if (!type_void.equals(rettype))


                adderreur("return not void", "return must be void", ret.start.getLine());


        }

        popscope();
    }


    private void deuxiemepasse(EMJParser.FonctionContext ctx) {


        String funcnom = ctx.EMOJI_ID().getText();


        Symbol s = currentscope.lookup(funcnom, true);


        if (!(s instanceof Functionsymbol)) return;


        Functionsymbol funcsym = (Functionsymbol) s;


        String returntype = funcsym.returntype;


        pushscope(new Scope(currentscope, scopetype.FUNCTION, funcsym));


        if (ctx.parametres() != null) {

            for (EMJParser.ParametreContext p : ctx.parametres().parametre()) {

                String paramtype = typedutypecontext(p.type());

                String paramnom = p.EMOJI_ID().getText();

                currentscope.define(new Variablesymbol(paramnom, paramtype));


            }


        }


        for (EMJParser.InstructionContext instr : ctx.instruction()) visit(instr);


        EMJParser.Return_instruContext ret = ctx.return_instru();


        if (ret == null) {


            adderreur("oublié return", "func " + funcnom + " miss return", ctx.start.getLine());


        } else {


            String rettype = getreturntype(ret);


            if (!iscompatible(returntype, rettype))


                adderreur("ret", "expected " + returntype + " got " + rettype, ret.start.getLine());


        }

        popscope();
    }


    private String getreturntype(EMJParser.Return_instruContext ctx) {


        if (ctx.expressiondroite() != null) {


            return getexpressiontype(ctx.expressiondroite());


        } else if (ctx.VOID_TYPE() != null) {


            return type_void;


        } else {


            return type_void;


        }


    }


    @Override
    public Object visitDeclarationvariable(EMJParser.DeclarationvariableContext ctx) {

        String varname = ctx.EMOJI_ID().getText();

        String vartype = typedutypecontext(ctx.type());


        if (currentscope.symbols.containsKey(varname)) {


            adderreur("var declared ", "var  " + varname + " declared ", ctx.start.getLine());


            return null;


        }


        if (ctx.EQUAL() != null) {


            String inittype = getexpressiontype(ctx.expressiondroite());


            if (!iscompatible(vartype, inittype))


                adderreur("var", "can't init " + varname + " of type " + vartype + " with " + inittype, ctx.start.getLine());


        }


        currentscope.define(new Variablesymbol(varname, vartype));


        return null;


    }


    @Override
    public Object visitAffectation(EMJParser.AffectationContext ctx) {


        String varname = ctx.EMOJI_ID().getText();


        String vartype = null;

        String inittype = null;


        if (ctx.INT_TYPE() != null) {

            vartype = type_int;


            inittype = getexpressiontype(ctx.expressionentiere());


        } else if (ctx.STRING_TYPE() != null) {


            vartype = type_string;

            inittype = type_string;


        } else if (ctx.CHAR_TYPE() != null) {


            vartype = type_char;


            inittype = type_char;


        } else if (ctx.BOOL_TYPE() != null) {


            vartype = type_bool;


            inittype = getexpressiontype(ctx.expressionboolean());


        }


        if (currentscope.symbols.containsKey(varname)) {


            adderreur("var dec", "Variable " + varname + " already dec", ctx.start.getLine());

        } else if (!iscompatible(vartype, inittype)) {


            adderreur("varinit ", "type mism for " + varname, ctx.start.getLine());


        } else {


            currentscope.define(new Variablesymbol(varname, vartype));
        }
        return null;


    }


    @Override
    public Object visitAssign(EMJParser.AssignContext ctx) {

        String varname = ctx.expressiongauche().EMOJI_ID().getText();

        Symbol s = currentscope.lookup(varname, false);

        if (s == null || !(s instanceof Variablesymbol)) {

            adderreur("var non déclaré", "var " + varname + " not declared", ctx.start.getLine());
            return null;
        }

        String expectedtype = getexpressiontype(ctx.expressiongauche());

        if (expectedtype == null) {
            adderreur("invalid left expr", "cannot ... ", ctx.start.getLine());
            return null;
        }

        String righttypee = getexpressiontype(ctx.expressiondroite());

        if (!iscompatible(expectedtype, righttypee)) {
            adderreur("assign", "can't assign " + righttypee + " to " + expectedtype, ctx.start.getLine());
        }

        return null;
    }


    private void validateintproblem(String text, int line) {


        if (text.startsWith("0") && text.length() > 1) {


            adderreur("sta zero", "  ", line);


        }


        try {


            long val = Long.parseLong(text);


            if (val < Integer.MIN_VALUE || val > Integer.MAX_VALUE) {


                adderreur("int out ", "   ", line);


            }

        } catch (NumberFormatException e) {


            adderreur("invalid int", "  ", line);


        }
    }


    @Override
    public Object visitExpressiongauche(EMJParser.ExpressiongaucheContext ctx) {


        String varname = ctx.EMOJI_ID().getText();


        Symbol s = currentscope.lookup(varname, false);


        if (s == null) {


            adderreur("var not declaré ", "var " + varname + " not declared", ctx.start.getLine());


            return null;

        }


        if ((ctx.INDEX_ONE() != null || ctx.INDEX_TWO() != null) &&

                (!(s instanceof Variablesymbol) || !((Variablesymbol) s).type.startsWith(type_tuple_prefix))) {


            adderreur("not tuple", varname + " is not tuple", ctx.start.getLine());
        }

        return null;


    }


    @Override
    public Object visitAppelfonction(EMJParser.AppelfonctionContext ctx) {


        String funcname = ctx.EMOJI_ID().getText();


        Symbol s = currentscope.lookup(funcname, true);


        if (!(s instanceof Functionsymbol)) {


            adderreur("func nit declared ", "func " + funcname + " not declared", ctx.start.getLine());


            return null;


        }


        Functionsymbol func = (Functionsymbol) s;


        List<String> expected = func.paramtypes;


        List<String> provided = new ArrayList<>();


        if (ctx.arguments() != null) {


            for (EMJParser.ArgumentContext arg : ctx.arguments().argument()) {


                provided.add(getexpressiontype(arg.expressiondroite()));


            }
        }


        if (expected.size() != provided.size()) {


            adderreur("dd", "expected " + expected.size() + " args got " + provided.size(), ctx.start.getLine());
        } else {


            for (int i = 0; i < expected.size(); i++) {


                if (!iscompatible(expected.get(i), provided.get(i)))
                    adderreur("arg type match ", "arg " + (i + 1) + " type mis  match", ctx.start.getLine());
            }


        }


        return null;


    }


    @Override
    public Object visitRelation(EMJParser.RelationContext ctx) {


        if (ctx.expressionentiere().size() == 2) {


            String left = getexpressiontype(ctx.expressionentiere(0));


            String right = getexpressiontype(ctx.expressionentiere(1));


            if (!iscompatible(left, right))


                adderreur("invalid compar", "can't compare " + left + " with " + right, ctx.start.getLine());


        }


        return null;


    }


    private Integer getcoonst(EMJParser.ExpressionentiereContext expr) {
        return evalexpressionconst(expr);
    }


    private Integer evalexpressionconst(EMJParser.ExpressionentiereContext ctx) {
        if (ctx.terme().size() != 1) {
            return null;
        }
        return evaltermeconst(ctx.terme(0));
    }

    private Integer evaltermeconst(EMJParser.TermeContext ctx) {
        if (ctx.facteur().size() != 1) {
            return null;
        }
        return evalfacteurconst(ctx.facteur(0));
    }

    private Integer evalfacteurconst(EMJParser.FacteurContext ctx) {
        if (ctx.INT_VALUE() != null) {
            try {
                return Integer.parseInt(ctx.INT_VALUE().getText());
            } catch (NumberFormatException e) {
                return null;
            }
        }

        if (ctx.MINUS() != null) {
            Integer valeur = evalfacteurconst(ctx.facteur());
            if (valeur == null) {
                return null;
            }
            return -valeur;
        }

        if (ctx.expressionentiere() != null) {
            return evalexpressionconst(ctx.expressionentiere());
        }

        return null;
    }


    @Override
    public Object visitInstructionpredefinie(EMJParser.InstructionpredefinieContext ctx) {

        if (ctx.UP() != null || ctx.DOWN() != null || ctx.RIGHT() != null || ctx.LEFT() != null || ctx.CRAZY() != null) {

            String t = getexpressiontype(ctx.expressionentiere());
            if (!type_int.equals(t)) {
                adderreur("TYPE_ERR", "Invalid move", ctx.start.getLine());
            } else if (ctx.CRAZY() != null) {
                Integer val = evalexpressionconst(ctx.expressionentiere());
                if (val != null && (val < 1 || val > 5)) {
                    adderreur("CRAZY_RANGE", "Invalid duration (1-5)", ctx.start.getLine());
                }
            }
        }
        return null;
    }


    @Override
    public Object visitBloc(EMJParser.BlocContext ctx) {


        pushscope(new Scope(currentscope, scopetype.BLOCK));


        for (EMJParser.InstructionContext instr : ctx.instruction()) visit(instr);


        popscope();


        return null;


    }


    @Override
    public Object visitCondition(EMJParser.ConditionContext ctx) {


        String condtype = getexpressiontype(ctx.expressionboolean());


        if (!type_bool.equals(condtype))


            adderreur("condition not boolean", "condition must be boolean", ctx.start.getLine());


        visit(ctx.bloc(0));


        if (ctx.bloc().size() > 1) visit(ctx.bloc(1));


        return null;


    }


    @Override
    public Object visitBoucle(EMJParser.BoucleContext ctx) {

        if (ctx.WHILE() != null) {
            String condtype = getexpressiontype(ctx.expressionboolean());

            if (!type_bool.equals(condtype))
                adderreur("    ", "    ", ctx.start.getLine());

            visit(ctx.bloc());

        } else if (ctx.FOR() != null) {
            String counttype = getexpressiontype(ctx.expressionentiere());
            if (!type_int.equals(counttype))
                adderreur("TYPE_ERR", "Loop count must be an integer", ctx.start.getLine());

            Integer count = evalexpressionconst(ctx.expressionentiere());
            if (count != null && count <= 0) {
                adderreur("INVALID_LOOP_COUNT", "For loop count must be greater than 0", ctx.start.getLine());
            }

            visit(ctx.bloc());
        }
        return null;
    }


    enum scopetype {
        GLOBAL,

        FUNCTION,

        BLOCK

    }


    static class Scope {


        final Scope parent;


        final scopetype type;


        final Map<String, Symbol> symbols = new HashMap<>();


        final Functionsymbol associatedfunction;


        Scope(Scope parent, scopetype type) {

            this(parent, type, null);


        }


        Scope(Scope parent, scopetype type, Functionsymbol func) {


            this.parent = parent;


            this.type = type;


            this.associatedfunction = func;


        }


        void define(Symbol sym) {

            symbols.put(sym.getName(), sym);


        }


        Symbol lookup(String name, boolean globalonly) {


            Symbol s = symbols.get(name);


            if (s != null) return s;


            if (parent != null && !globalonly)

                return parent.lookup(name, false);


            if (parent != null && globalonly)

                return parent.lookup(name, true);


            return null;


        }
    }


    interface Symbol {


        String getName();


    }


    static class Variablesymbol implements Symbol {


        final String name;


        final String type;


        Variablesymbol(String name, String type) {

            this.name = name;


            this.type = type;


        }

        @Override
        public String getName() {


            return name;


        }


    }


    static class Parametersymbol {
        final String name;


        final String type;


        Parametersymbol(String name, String type) {


            this.name = name;


            this.type = type;


        }


    }


    static class Functionsymbol implements Symbol {


        final String name;


        final String returntype;


        final List<String> paramtypes;


        Functionsymbol(String name, String returntype, List<Parametersymbol> params) {


            this.name = name;

            this.returntype = returntype;


            this.paramtypes = new ArrayList<>();


            for (Parametersymbol p : params) paramtypes.add(p.type);


        }


        @Override


        public String getName() {


            return name;


        }


    }


}